use_frameworks!

platform :ios, '10.0'

target 'moduleTest_Example' do
  pod 'moduleTest', :path => '../'

  target 'moduleTest_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
